trigger:
- main  # O la rama que prefieras

pool:
  name: NombreDelPool  # Reemplaza con el nombre del pool de agentes

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python hello.py
  displayName: 'Run Hello World Script'
