trigger:
- main  # O la rama que prefieras

pool:
  name: agenteWLeo  # Reemplaza con el nombre del pool de agentes

steps:
- script: |
    python --version
    python hello.py
  displayName: 'Run Hello World Script'
